import React, { useState } from 'react';

function App() {
  const [prompt, setPrompt] = useState('');
  const [email, setEmail] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [copied, setCopied] = useState(false);
  const [emailSent, setEmailSent] = useState(false);

  const generateList = async () => {
    if (!prompt.trim()) return;
    
    setLoading(true);
    setResult(null);
    setEmailSent(false);
    
    try {
      const response = await fetch('https://ai4u-top10-backend.vercel.app/api/generate-list', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ 
          prompt: prompt.trim(),
          email: email.trim() 
        }),
      });
      
      const data = await response.json();
      
      if (data.success) {
        setResult(data);
        if (email.trim()) {
          setEmailSent(true);
        }
      } else {
        setResult({
          success: false,
          error: data.error || 'Failed to generate list'
        });
      }
    } catch (error) {
      setResult({
        success: false,
        error: 'Network error - please try again'
      });
    } finally {
      setLoading(false);
    }
  };

  const shareToSocial = (platform) => {
    if (!result?.share_url) return;
    
    const shareUrls = {
      facebook: `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(result.share_url)}`,
      twitter: `https://twitter.com/intent/tweet?url=${encodeURIComponent(result.share_url)}&text=${encodeURIComponent('Check out this AI-researched Top 10 list!')}`,
      linkedin: `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(result.share_url)}`,
      whatsapp: `https://wa.me/?text=${encodeURIComponent(`Check out this Top 10 list: ${result.share_url}`)}`,
      email: `mailto:?subject=${encodeURIComponent('Top 10 List')}&body=${encodeURIComponent(`Check out this list: ${result.share_url}`)}`
    };
    
    window.open(shareUrls[platform], '_blank', 'width=600,height=400');
  };

  const copyToClipboard = () => {
    if (!result || !result.success) return;
    
    const htmlContent = generateHTMLOutput(result);
    navigator.clipboard.writeText(htmlContent).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const generateHTMLOutput = (data) => {
    const productsHTML = data.products.map((product, index) => `
      <div style="border: 1px solid #ddd; margin: 10px 0; padding: 15px; border-radius: 8px;">
        <h3 style="color: #232F3E;">${index + 1}. ${product.title}</h3>
        <div style="display: flex; align-items: center; margin: 5px 0;">
          <span style="color: #FF9900; font-weight: bold;">${product.price}</span>
          <span style="margin-left: 15px; color: #565959;">⭐ ${product.rating}/5</span>
        </div>
        <p style="color: #565959; margin: 10px 0;">${product.description}</p>
        <a href="${product.affiliate_link}" target="_blank" 
           style="background: #FF9900; color: white; padding: 10px 20px; text-decoration: none; border-radius: 4px; display: inline-block;">
          View on Amazon
        </a>
      </div>
    `).join('');

    return `
      <div style="max-width: 800px; margin: 0 auto; font-family: Arial, sans-serif;">
        <h1 style="color: #232F3E; text-align: center;">${data.title}</h1>
        <p style="color: #565959; text-align: center; margin: 20px 0;">${data.intro}</p>
        ${productsHTML}
        <p style="text-align: center; color: #565959; font-size: 12px; margin-top: 30px;">
          Generated by AI4U Top 10 Lists • ${data.generated_at}
        </p>
      </div>
    `;
  };

  return (
    <div style={{ minHeight: '100vh', background: 'linear-gradient(135deg, #4338ca 0%, #7c3aed 50%, #ec4899 100%)', padding: '20px', color: 'white' }}>
      <div style={{ maxWidth: '1200px', margin: '0 auto' }}>
        
        {/* Header */}
        <div style={{ textAlign: 'center', marginBottom: '40px' }}>
          <h1 style={{ fontSize: '3.5rem', fontWeight: 'bold', marginBottom: '16px' }}>
            AI4U Top 10 Lists ✨
          </h1>
          <p style={{ fontSize: '1.2rem', opacity: '0.9', maxWidth: '600px', margin: '0 auto' }}>
            AI-Researched & Endorsed Amazon Products - Now with REAL data and working affiliate links!
          </p>
        </div>

        {/* Input Section */}
        <div style={{ maxWidth: '600px', margin: '0 auto 40px auto' }}>
          <div style={{ background: 'rgba(255,255,255,0.1)', backdropFilter: 'blur(10px)', borderRadius: '20px', padding: '30px', border: '1px solid rgba(255,255,255,0.2)' }}>
            
            <div style={{ marginBottom: '20px' }}>
              <label style={{ display: 'block', fontSize: '14px', fontWeight: '500', marginBottom: '8px' }}>
                What products are you looking for?
              </label>
              <input
                type="text"
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder="e.g., organic potato chips, baby diapers, gaming laptops..."
                style={{ 
                  width: '100%', 
                  padding: '12px 16px', 
                  borderRadius: '8px', 
                  border: '1px solid rgba(255,255,255,0.3)',
                  background: 'rgba(255,255,255,0.2)',
                  color: 'white',
                  fontSize: '16px',
                  outline: 'none'
                }}
                onKeyPress={(e) => e.key === 'Enter' && !loading && generateList()}
              />
            </div>

            <div style={{ marginBottom: '20px' }}>
              <label style={{ display: 'block', fontSize: '14px', fontWeight: '500', marginBottom: '8px' }}>
                Email address (optional - to receive your list)
              </label>
              <input
                type="email"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                placeholder="your@email.com"
                style={{ 
                  width: '100%', 
                  padding: '12px 16px', 
                  borderRadius: '8px', 
                  border: '1px solid rgba(255,255,255,0.3)',
                  background: 'rgba(255,255,255,0.2)',
                  color: 'white',
                  fontSize: '16px',
                  outline: 'none'
                }}
              />
            </div>
            
            <button
              onClick={generateList}
              disabled={loading || !prompt.trim()}
              style={{ 
                width: '100%', 
                padding: '15px', 
                background: loading ? '#666' : 'linear-gradient(135deg, #9333ea 0%, #ec4899 100%)', 
                color: 'white', 
                border: 'none', 
                borderRadius: '8px', 
                fontSize: '18px',
                fontWeight: '600',
                cursor: loading ? 'not-allowed' : 'pointer',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                gap: '8px'
              }}
            >
              {loading ? 'Researching Products...' : 'Generate Top 10 List'}
            </button>
          </div>
        </div>

        {/* Results */}
        {result && (
          <div style={{ maxWidth: '1000px', margin: '0 auto' }}>
            {result.success ? (
              <div style={{ background: 'rgba(255,255,255,0.1)', backdropFilter: 'blur(10px)', borderRadius: '20px', padding: '30px', border: '1px solid rgba(255,255,255,0.2)' }}>
                
                {/* Header */}
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '30px', flexWrap: 'wrap', gap: '20px' }}>
                  <div style={{ flex: 1 }}>
                    <h2 style={{ fontSize: '2rem', fontWeight: 'bold', marginBottom: '8px' }}>
                      {result.title}
                    </h2>
                    <p style={{ opacity: '0.9', marginBottom: '8px' }}>
                      {result.intro}
                    </p>
                    <p style={{ fontSize: '14px', color: '#86efac' }}>
                      ✅ All products have REAL Amazon ASINs and working affiliate links!
                    </p>
                    {emailSent && (
                      <p style={{ fontSize: '14px', color: '#93c5fd', marginTop: '4px' }}>
                        📧 List sent to your email!
                      </p>
                    )}
                  </div>
                  <button
                    onClick={copyToClipboard}
                    style={{ 
                      background: '#16a34a', 
                      color: 'white', 
                      padding: '10px 20px', 
                      border: 'none', 
                      borderRadius: '8px',
                      cursor: 'pointer',
                      fontSize: '14px',
                      fontWeight: '500'
                    }}
                  >
                    {copied ? '✅ Copied!' : '📋 Copy HTML'}
                  </button>
                </div>

                {/* Share Section */}
                <div style={{ marginBottom: '30px', padding: '20px', background: 'rgba(255,255,255,0.1)', borderRadius: '12px' }}>
                  <h3 style={{ fontSize: '18px', fontWeight: '600', marginBottom: '15px', display: 'flex', alignItems: 'center', gap: '8px' }}>
                    🔗 Share this list
                  </h3>
                  <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px', marginBottom: '15px' }}>
                    <button onClick={() => shareToSocial('facebook')} style={{ background: '#1877f2', color: 'white', padding: '8px 16px', border: 'none', borderRadius: '6px', fontSize: '14px', cursor: 'pointer' }}>
                      📘 Facebook
                    </button>
                    <button onClick={() => shareToSocial('twitter')} style={{ background: '#1da1f2', color: 'white', padding: '8px 16px', border: 'none', borderRadius: '6px', fontSize: '14px', cursor: 'pointer' }}>
                      🐦 Twitter
                    </button>
                    <button onClick={() => shareToSocial('linkedin')} style={{ background: '#0077b5', color: 'white', padding: '8px 16px', border: 'none', borderRadius: '6px', fontSize: '14px', cursor: 'pointer' }}>
                      💼 LinkedIn
                    </button>
                    <button onClick={() => shareToSocial('whatsapp')} style={{ background: '#25d366', color: 'white', padding: '8px 16px', border: 'none', borderRadius: '6px', fontSize: '14px', cursor: 'pointer' }}>
                      💬 WhatsApp
                    </button>
                    <button onClick={() => shareToSocial('email')} style={{ background: '#6b7280', color: 'white', padding: '8px 16px', border: 'none', borderRadius: '6px', fontSize: '14px', cursor: 'pointer' }}>
                      ✉️ Email
                    </button>
                  </div>
                  <input
                    type="text"
                    value={result.share_url || 'https://ai4u-top10-lists.vercel.app'}
                    readOnly
                    onClick={(e) => e.target.select()}
                    style={{ 
                      width: '100%', 
                      padding: '8px 12px', 
                      background: 'rgba(255,255,255,0.2)', 
                      border: '1px solid rgba(255,255,255,0.3)', 
                      color: 'white', 
                      fontSize: '14px', 
                      borderRadius: '4px'
                    }}
                  />
                </div>

                {/* Products */}
                <div style={{ display: 'grid', gap: '16px' }}>
                  {result.products && result.products.map((product, index) => (
                    <div key={product.asin} style={{ background: 'rgba(255,255,255,0.2)', borderRadius: '12px', padding: '20px', border: '1px solid rgba(255,255,255,0.3)' }}>
                      <div style={{ display: 'flex', alignItems: 'flex-start', gap: '16px' }}>
                        <div style={{ width: '48px', height: '48px', background: 'linear-gradient(135deg, #9333ea 0%, #ec4899 100%)', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'white', fontWeight: 'bold', fontSize: '18px', flexShrink: 0 }}>
                          {index + 1}
                        </div>
                        
                        <div style={{ flex: 1 }}>
                          <h3 style={{ fontSize: '1.1rem', fontWeight: '600', marginBottom: '8px' }}>
                            {product.title}
                          </h3>
                          
                          <div style={{ display: 'flex', alignItems: 'center', gap: '16px', marginBottom: '8px' }}>
                            <span style={{ color: '#86efac', fontWeight: 'bold', fontSize: '1.25rem' }}>
                              {product.price}
                            </span>
                            <div style={{ display: 'flex', alignItems: 'center', gap: '4px' }}>
                              <span style={{ color: '#fbbf24' }}>⭐</span>
                              <span>{product.rating}/5</span>
                            </div>
                          </div>
                          
                          <p style={{ opacity: '0.9', fontSize: '14px', marginBottom: '12px' }}>
                            {product.description}
                          </p>
                          
                          <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
                            
                              href={product.affiliate_link}
                              target="_blank"
                              rel="noopener noreferrer"
                              style={{ 
                                background: '#f97316', 
                                color: 'white', 
                                padding: '8px 16px', 
                                textDecoration: 'none', 
                                borderRadius: '6px', 
                                fontSize: '14px',
                                fontWeight: '500',
                                display: 'flex',
                                alignItems: 'center',
                                gap: '4px'
                              }}
                            >
                              🛒 View on Amazon
                            </a>
                            <span style={{ fontSize: '12px', color: '#86efac', padding: '4px 8px' }}>
                              ASIN: {product.asin}
                            </span>
                          </div>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>

                {/* Footer */}
                <div style={{ marginTop: '30px', paddingTop: '20px', borderTop: '1px solid rgba(255,255,255,0.2)', textAlign: 'center' }}>
                  <p style={{ fontSize: '14px', opacity: '0.8' }}>
                    Generated: {result.generated_at} | Affiliate ID: {result.affiliate_id}
                  </p>
                  <p style={{ fontSize: '12px', opacity: '0.7', marginTop: '4px' }}>
                    All links are functional and revenue-ready ✅
                  </p>
                </div>
              </div>
            ) : (
              <div style={{ background: 'rgba(239, 68, 68, 0.2)', border: '1px solid rgba(239, 68, 68, 0.5)', borderRadius: '8px', padding: '16px' }}>
                <p style={{ color: '#fca5a5' }}>
                  Error: {result.error}
                </p>
              </div>
            )}
          </div>
        )}

        {/* Features */}
        <div style={{ maxWidth: '1000px', margin: '40px auto 0 auto', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '16px' }}>
          <div style={{ background: 'rgba(255,255,255,0.1)', backdropFilter: 'blur(10px)', borderRadius: '12px', padding: '20px', border: '1px solid rgba(255,255,255,0.2)', textAlign: 'center' }}>
            <h3 style={{ fontWeight: '600', marginBottom: '8px' }}>🎯 Unlimited Categories</h3>
            <p style={{ fontSize: '14px', opacity: '0.8' }}>From potato chips to baby products - any category works!</p>
          </div>
          <div style={{ background: 'rgba(255,255,255,0.1)', backdropFilter: 'blur(10px)', borderRadius: '12px', padding: '20px', border: '1px solid rgba(255,255,255,0.2)', textAlign: 'center' }}>
            <h3 style={{ fontWeight: '600', marginBottom: '8px' }}>✅ Real Amazon Data</h3>
            <p style={{ fontSize: '14px', opacity: '0.8' }}>Actual ASINs, current prices, real customer ratings</p>
          </div>
          <div style={{ background: 'rgba(255,255,255,0.1)', backdropFilter: 'blur(10px)', borderRadius: '12px', padding: '20px', border: '1px solid rgba(255,255,255,0.2)', textAlign: 'center' }}>
            <h3 style={{ fontWeight: '600', marginBottom: '8px' }}>💰 Revenue Ready</h3>
            <p style={{ fontSize: '14px', opacity: '0.8' }}>Working affiliate links with your ID: ai4u0c-20</p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default App;
