import React, { useState } from 'react';

function App() {
  const [prompt, setPrompt] = useState('');
  const [email, setEmail] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [copied, setCopied] = useState(false);

  const generateList = async () => {
    if (!prompt.trim()) return;

    setLoading(true);
    setResult(null);

    try {
      const response = await fetch('https://ai4u-top10-backend.vercel.app/api/generate-list', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          prompt: prompt.trim(),
          email: email.trim()
        }),
      });

      const data = await response.json();
      setResult(data);
    } catch (error) {
      setResult({
        success: false,
        error: 'Network error - please try again'
      });
    } finally {
      setLoading(false);
    }
  };

  const copyToClipboard = () => {
    if (!result || !result.success) return;

    const htmlContent = `
      <div style="max-width: 800px; margin: 0 auto; font-family: Arial, sans-serif;">
        <h1 style="color: #232F3E; text-align: center;">${result.title}</h1>
        <p style="color: #565959; text-align: center; margin: 20px 0;">${result.intro}</p>
        ${result.products.map((product, index) => `
          <div style="border: 1px solid #ddd; margin: 10px 0; padding: 15px; border-radius: 8px;">
            <h3 style="color: #232F3E;">${index + 1}. ${product.title}</h3>
            <p><strong>Price:</strong> ${product.price}</p>
            <p><strong>Rating:</strong> ${product.rating}/5 ⭐</p>
            <p>${product.description}</p>
            <a href="${product.affiliate_link}" target="_blank" style="background: #FF9900; color: white; padding: 10px 20px; text-decoration: none; border-radius: 4px; display: inline-block; margin-top: 10px;">View on Amazon</a>
          </div>
        `).join('')}
        <p style="text-align: center; color: #565959; font-size: 12px; margin-top: 30px;">Generated by AI4U Top 10 Lists</p>
      </div>
    `;

    navigator.clipboard.writeText(htmlContent).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const shareToFacebook = () => {
    const url = encodeURIComponent(window.location.href);
    window.open(`https://www.facebook.com/sharer/sharer.php?u=${url}`, '_blank');
  };

  const shareToTwitter = () => {
    const url = encodeURIComponent(window.location.href);
    const text = encodeURIComponent('Check out this AI-researched Top 10 list!');
    window.open(`https://twitter.com/intent/tweet?url=${url}&text=${text}`, '_blank');
  };

  return (
    <div style={{
      minHeight: '100vh',
      background: 'linear-gradient(135deg, #4338ca 0%, #7c3aed 50%, #ec4899 100%)',
      padding: '20px',
      color: 'white',
      fontFamily: 'Arial, sans-serif'
    }}>
      <div style={{ maxWidth: '1200px', margin: '0 auto' }}>

        {/* Header */}
        <div style={{ textAlign: 'center', marginBottom: '40px' }}>
          <h1 style={{ fontSize: '3rem', fontWeight: 'bold', marginBottom: '16px', margin: '0 0 16px 0' }}>
            AI4U Top 10 Lists ✨
          </h1>
          <p style={{ fontSize: '1.2rem', opacity: '0.9', maxWidth: '600px', margin: '0 auto' }}>
            AI-Researched & Endorsed Amazon Products - Real data and working affiliate links!
          </p>
        </div>

        {/* Input Section */}
        <div style={{ maxWidth: '600px', margin: '0 auto 40px auto' }}>
          <div style={{
            background: 'rgba(255,255,255,0.1)',
            borderRadius: '20px',
            padding: '30px',
            border: '1px solid rgba(255,255,255,0.2)'
          }}>

            <div style={{ marginBottom: '20px' }}>
              <label style={{ display: 'block', fontSize: '14px', fontWeight: '500', marginBottom: '8px' }}>
                What products are you looking for?
              </label>
              <input
                type="text"
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder="e.g., organic potato chips, baby diapers, gaming laptops..."
                style={{
                  width: '100%',
                  padding: '12px 16px',
                  borderRadius: '8px',
                  border: '1px solid rgba(255,255,255,0.3)',
                  background: 'rgba(255,255,255,0.2)',
                  color: 'white',
                  fontSize: '16px',
                  outline: 'none',
                  boxSizing: 'border-box'
                }}
                onKeyPress={(e) => e.key === 'Enter' && !loading && generateList()}
              />
            </div>

            <div style={{ marginBottom: '20px' }}>
             <label style={{ display: 'block', fontSize: '14px', fontWeight: '500', marginBottom: '8px' }}>
  Email address (optional - to receive your list)
</label>
<input
  type="email"
  value={email}
  onChange={(e) => setEmail(e.target.value)}
  placeholder="leehanna8@gmail.com"
  style={{
    width: '100%',
    padding: '12px 16px',
    borderRadius: '8px',
    border: '1px solid rgba(255,255,255,0.3)',
    background: 'rgba(255,255,255,0.2)',
    color: 'white',
    fontSize: '16px',
    outline: 'none',
    boxSizing: 'border-box'
  }}
/>
    </div>
  </div>
</div>
